# Generated by Django 4.2.7 on 2025-09-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='장소명')),
                ('area', models.CharField(max_length=100, verbose_name='지역')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='평점')),
                ('duration', models.CharField(max_length=50, verbose_name='소요시간')),
                ('short_description', models.TextField(verbose_name='간단 설명')),
                ('long_description', models.TextField(verbose_name='상세 설명')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '여행지',
                'verbose_name_plural': '여행지들',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
            },
        ),
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, verbose_name='지역')),
                ('weather_type', models.CharField(choices=[('현재', '현재'), ('단기', '단기'), ('중기', '중기')], max_length=10, verbose_name='타입')),
                ('date', models.CharField(max_length=8, verbose_name='날짜')),
                ('time', models.CharField(max_length=10, verbose_name='시간')),
                ('category', models.CharField(max_length=50, verbose_name='항목')),
                ('value', models.CharField(max_length=100, verbose_name='값')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '날씨 데이터',
                'verbose_name_plural': '날씨 데이터들',
                'ordering': ['-date', '-time'],
                'unique_together': {('region', 'weather_type', 'date', 'time', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='여행 제목')),
                ('duration', models.CharField(max_length=50, verbose_name='여행 기간')),
                ('style', models.CharField(max_length=50, verbose_name='여행 스타일')),
                ('budget', models.CharField(max_length=50, verbose_name='예산')),
                ('companions', models.CharField(max_length=50, verbose_name='동행자')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='destinations.user')),
            ],
            options={
                'verbose_name': '여행 계획',
                'verbose_name_plural': '여행 계획들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='destinations.user')),
            ],
            options={
                'verbose_name': '찜 목록',
                'verbose_name_plural': '찜 목록들',
                'unique_together': {('user', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='DestinationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='태그명')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='destinations.destination')),
            ],
            options={
                'verbose_name': '여행지 태그',
                'verbose_name_plural': '여행지 태그들',
                'unique_together': {('destination', 'tag_name')},
            },
        ),
    ]
