# Generated by Django 4.2.7 on 2025-09-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherdata',
            options={'ordering': ['-date', '-time'], 'verbose_name': '날씨 데이터 (구버전)', 'verbose_name_plural': '날씨 데이터들 (구버전)'},
        ),
        migrations.CreateModel(
            name='ShortForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, verbose_name='지역')),
                ('date', models.CharField(max_length=8, verbose_name='날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('forecast_time', models.CharField(max_length=4, verbose_name='예보시간')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='기온(℃)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='풍속(m/s)')),
                ('precipitation', models.CharField(blank=True, max_length=20, null=True, verbose_name='강수형태')),
            ],
            options={
                'verbose_name': '단기 예보',
                'verbose_name_plural': '단기 예보들',
                'ordering': ['-date', 'forecast_time'],
                'unique_together': {('region', 'date', 'forecast_time')},
            },
        ),
        migrations.CreateModel(
            name='MidForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, verbose_name='지역')),
                ('date', models.CharField(max_length=8, verbose_name='날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(max_length=10, verbose_name='예보구간')),
                ('weather_condition', models.CharField(blank=True, max_length=50, null=True, verbose_name='날씨')),
                ('rain_probability', models.IntegerField(blank=True, null=True, verbose_name='강수확률(%)')),
                ('min_temperature', models.FloatField(blank=True, null=True, verbose_name='최저기온(℃)')),
                ('max_temperature', models.FloatField(blank=True, null=True, verbose_name='최고기온(℃)')),
            ],
            options={
                'verbose_name': '중기 예보',
                'verbose_name_plural': '중기 예보들',
                'ordering': ['-date', 'period'],
                'unique_together': {('region', 'date', 'period')},
            },
        ),
        migrations.CreateModel(
            name='CurrentWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50, verbose_name='지역')),
                ('date', models.CharField(max_length=8, verbose_name='날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time', models.CharField(max_length=4, verbose_name='관측시간')),
                ('temperature', models.FloatField(blank=True, null=True, verbose_name='기온(℃)')),
                ('humidity', models.IntegerField(blank=True, null=True, verbose_name='습도(%)')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='풍속(m/s)')),
                ('rainfall', models.FloatField(blank=True, null=True, verbose_name='강수량(mm)')),
            ],
            options={
                'verbose_name': '현재 날씨',
                'verbose_name_plural': '현재 날씨들',
                'ordering': ['-date', '-time'],
                'unique_together': {('region', 'date', 'time')},
            },
        ),
    ]
