# Generated by Django 4.2.7 on 2025-09-22 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0002_alter_weatherdata_options_shortforecast_midforecast_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WeatherData',
        ),
    ]
