# Generated by Django 4.2.7 on 2025-10-30 03:40

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberTrip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PLANNED', '계획됨'), ('COMPLETED', '완료됨'), ('RECOMMENDED', '추천됨')], max_length=20)),
                ('trip_title', models.CharField(max_length=200)),
                ('travel_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'member_trip',
                'ordering': ['travel_date'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberTripItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.SmallIntegerField()),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('stay_time', models.DurationField(blank=True, null=True)),
            ],
            options={
                'db_table': 'member_trip_itinerary',
                'ordering': ['trip_id', 'seq'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyVectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RAG 벡터',
                'verbose_name_plural': 'RAG 벡터들',
                'db_table': 'my_vectors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TouristDetail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content_id', models.CharField(max_length=20)),
                ('address_code', models.CharField(blank=True, max_length=20, null=True)),
                ('sigungu_name', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('map_x', models.FloatField(blank=True, null=True)),
                ('map_y', models.FloatField(blank=True, null=True)),
                ('intro_serial_num', models.CharField(blank=True, max_length=50, null=True)),
                ('content_type_id', models.CharField(blank=True, max_length=20, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('restdate', models.CharField(blank=True, max_length=500, null=True)),
                ('useseason', models.CharField(blank=True, max_length=500, null=True)),
                ('usetime', models.CharField(blank=True, max_length=500, null=True)),
                ('is_parking', models.CharField(blank=True, max_length=20, null=True)),
                ('is_baby_carriage', models.CharField(blank=True, max_length=20, null=True)),
                ('is_pet', models.CharField(blank=True, max_length=20, null=True)),
                ('is_credit_card', models.CharField(blank=True, max_length=20, null=True)),
                ('info_serial_num', models.CharField(blank=True, max_length=50, null=True)),
                ('info_name', models.CharField(blank=True, max_length=200, null=True)),
                ('info_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tourist_spot_detail',
                'ordering': ['content_id', 'info_name', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('content_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('firstimage', models.CharField(blank=True, max_length=500, null=True)),
                ('firstimage2', models.CharField(blank=True, max_length=500, null=True)),
                ('category_code', models.CharField(blank=True, max_length=20, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tourist_spot',
                'managed': False,
            },
        ),
    ]
