# Generated by Django 4.2.7 on 2025-10-20 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTable',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '코드 테이블',
                'verbose_name_plural': '코드 테이블들',
                'db_table': 'code_table',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jjim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jjim_on_off', models.BooleanField()),
            ],
            options={
                'verbose_name': '찜',
                'verbose_name_plural': '찜 목록',
                'db_table': 'jjim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLANNED', '계획됨'), ('COMPLETED', '완료됨'), ('RECOMMENDED', '추천됨')], max_length=20)),
                ('trip_title', models.CharField(max_length=100)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '회원 여행',
                'verbose_name_plural': '회원 여행들',
                'db_table': 'member_trip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MemberTripItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.SmallIntegerField()),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('stay_time', models.DurationField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '여행 일정',
                'verbose_name_plural': '여행 일정들',
                'db_table': 'member_trip_itinerary',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyVectors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.VectorField(dimensions=1536)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RAG 벡터',
                'verbose_name_plural': 'RAG 벡터들',
                'db_table': 'my_vectors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TouristSpot',
            fields=[
                ('content_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('firstimage', models.CharField(blank=True, max_length=500, null=True)),
                ('firstimage2', models.CharField(blank=True, max_length=500, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '관광지',
                'verbose_name_plural': '관광지들',
                'db_table': 'tourist_spot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TouristSpotDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigungu_name', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('map_x', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('map_y', models.DecimalField(blank=True, decimal_places=6, max_digits=11, null=True)),
                ('intro_serial_num', models.IntegerField(blank=True, null=True)),
                ('content_type_id', models.CharField(blank=True, max_length=10, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('restdate', models.TextField(blank=True, null=True)),
                ('useseason', models.TextField(blank=True, null=True)),
                ('usetime', models.TextField(blank=True, null=True)),
                ('is_parking', models.SmallIntegerField(blank=True, null=True)),
                ('is_baby_carriage', models.SmallIntegerField(blank=True, null=True)),
                ('is_pet', models.SmallIntegerField(blank=True, null=True)),
                ('is_credit_card', models.SmallIntegerField(blank=True, null=True)),
                ('info_serial_num', models.CharField(blank=True, max_length=50, null=True)),
                ('info_name', models.CharField(blank=True, max_length=200, null=True)),
                ('info_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '관광지 상세정보',
                'verbose_name_plural': '관광지 상세정보들',
                'db_table': 'tourist_spot_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='장소명')),
                ('area', models.CharField(max_length=100, verbose_name='지역')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='평점')),
                ('duration', models.CharField(max_length=50, verbose_name='소요시간')),
                ('short_description', models.TextField(verbose_name='간단 설명')),
                ('long_description', models.TextField(verbose_name='상세 설명')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='이미지 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '여행지',
                'verbose_name_plural': '여행지들',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='여행 제목')),
                ('duration', models.CharField(max_length=50, verbose_name='여행 기간')),
                ('style', models.CharField(max_length=50, verbose_name='여행 스타일')),
                ('budget', models.CharField(max_length=50, verbose_name='예산')),
                ('companions', models.CharField(max_length=50, verbose_name='동행자')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '여행 계획',
                'verbose_name_plural': '여행 계획들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='destinations.destination')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '찜 목록',
                'verbose_name_plural': '찜 목록들',
                'unique_together': {('user', 'destination')},
            },
        ),
        migrations.CreateModel(
            name='DestinationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50, verbose_name='태그명')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='destinations.destination')),
            ],
            options={
                'verbose_name': '여행지 태그',
                'verbose_name_plural': '여행지 태그들',
                'unique_together': {('destination', 'tag_name')},
            },
        ),
    ]
