# # Generated by Django 4.2.7 on 2025-09-26 01:43

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('destinations', '0003_remove_weatherdata'),
#     ]

#     operations = [
#         migrations.DeleteModel(
#             name='CurrentWeather',
#         ),
#         migrations.DeleteModel(
#             name='MidForecast',
#         ),
#         migrations.DeleteModel(
#             name='ShortForecast',
#         ),
#     ]
